{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app.kubernetes.io/name: python-web
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ .Release.Name }}-postgres-headless
  replicas: {{ .Values.postgres.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: python-web
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-web
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.auth.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.auth.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.auth.password }}"
          ports:
            - containerPort: {{ .Values.postgres.port }}
              name: postgres
          livenessProbe:
            tcpSocket:
              port: {{ .Values.postgres.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.postgres.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
      {{- if or (not .Values.postgres.persistence.enabled) (and .Values.postgres.persistence.enabled (not .Values.postgres.persistence.storageClassName) .Values.postgres.persistence.fallbackToEmptyDir) }}
      volumes:
        - name: postgres-data
          emptyDir: {}
      {{- end }}
  {{- if and .Values.postgres.persistence.enabled (or .Values.postgres.persistence.storageClassName (not .Values.postgres.persistence.fallbackToEmptyDir)) }}
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.postgres.persistence.storageClassName }}
        storageClassName: {{ .Values.postgres.persistence.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}
  {{- end }}
{{- end }}

