apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app.kubernetes.io/name: python-web
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  {{- with .Values.web.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app.kubernetes.io/name: python-web
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: 8000
